// --- 画像アップロード ---
const imageInput = document.getElementById('image-input');
const portraitPreview = document.getElementById('portrait-preview');
const uploadText = document.getElementById('upload-text');

imageInput.addEventListener('change', function(e) {
  const file = e.target.files[0];
  if (file) {
    const reader = new FileReader();
    reader.onload = function(event) {
      portraitPreview.src = event.target.result;
      portraitPreview.style.opacity = 1;
      uploadText.style.display = 'none';
    }
    reader.readAsDataURL(file);
  }
});

// --- ランダムIDと日付の自動生成 ---
function setAutoGeneratedData() {
  // ID生成
  const idNumberEl = document.getElementById('id-number');
  const digits = Math.floor(1000 + Math.random() * 9000); 
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let randomChars = '';
  for (let i = 0; i < 4; i++) {
    randomChars += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  idNumberEl.textContent = `NO. ${digits}-${randomChars}`;

  // 日付生成
  const issueEl = document.getElementById('issue-date');
  const renewEl = document.getElementById('renew-date');
  const now = new Date();
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');

  issueEl.textContent = `${yyyy}.${mm}.${dd}`;
  renewEl.textContent = `${yyyy + 1}.${mm}.${dd}`;
}
setAutoGeneratedData();

// --- 性別ドロップダウンの特殊ギミック ---
const genderSelect = document.getElementById('gender-select');
const genderFull = ['♀（メス）', '♂（オス）', '⚥（両性、両性具有）', '⚲（性別なし）'];
const genderShort = ['♀', '♂', '⚥', '⚲'];

// 選択肢のテキストを切り替える関数
function setGenderText(isFull) {
  const options = genderSelect.options;
  for (let i = 0; i < options.length; i++) {
    options[i].text = isFull ? genderFull[i] : genderShort[i];
  }
}

// 初期状態は記号のみ
setGenderText(false);

// 開いた時（フォーカス時）は説明付きテキストにする
genderSelect.addEventListener('focus', () => {
  setGenderText(true);
});

// 閉じた時（フォーカスが外れた時）は記号のみに戻す
genderSelect.addEventListener('blur', () => {
  setGenderText(false);
  if (genderSelect.value) {
    genderSelect.classList.add('is-pink');
  }
});

// 選択直後に自動で閉じる（フォーカスを外す）
genderSelect.addEventListener('change', () => {
  genderSelect.blur(); 
});


// --- 名前入力欄の装飾 ---
const nameInput = document.getElementById('name-input');
function updateNameUnderline() {
  const val = nameInput.value.trim();
  if (val === "CHARACTER NAME" || val === "") {
    nameInput.classList.remove('is-pink');
  } else {
    nameInput.classList.add('is-pink');
  }
}
nameInput.addEventListener('blur', updateNameUnderline);


// --- 画像として出力する処理 ---
const downloadBtn = document.getElementById('download-btn');
const sheet = document.getElementById('character-sheet');

downloadBtn.addEventListener('click', () => {
  const originalText = downloadBtn.textContent;
  downloadBtn.textContent = 'GENERATING...';
  downloadBtn.disabled = true;

  const clone = sheet.cloneNode(true);

  // html2canvasバグ回避のため、入力フォームをdiv要素に変換
  const originalInputs = sheet.querySelectorAll('input:not([type="file"]), select, textarea');
  const clonedInputs = clone.querySelectorAll('input:not([type="file"]), select, textarea');
  
  originalInputs.forEach((input, i) => {
    const cInput = clonedInputs[i];
    const div = document.createElement('div');
    div.className = cInput.className;
    
    if (input.tagName === 'SELECT') {
      div.textContent = input.options[input.selectedIndex].text;
      div.style.display = 'flex';
      div.style.alignItems = 'center';
      
      // 性別アイコンの場合は中央寄せと大文字化を引き継ぐ
      if (input.id === 'gender-select') {
        div.style.justifyContent = 'center';
        div.style.fontSize = '1.8rem';
        div.style.color = 'var(--neon-pink)';
        div.style.textShadow = '0 0 5px var(--neon-pink)';
      }
    } else {
      div.textContent = input.value;
      if (input.tagName === 'TEXTAREA') {
        div.style.whiteSpace = 'pre-wrap';
      }
    }
    
    // 下線の引き継ぎ
    if (input.id === 'name-input' || input.id === 'gender-select') {
      div.style.lineHeight = '1.3';
      div.style.height = 'auto';
      div.style.paddingBottom = '0.5rem';
      div.style.borderBottom = input.classList.contains('is-pink') ? '2px solid var(--neon-pink)' : '2px solid rgba(255, 255, 255, 0.3)';
    }

    cInput.parentNode.replaceChild(div, cInput);
  });

  // PCレイアウトの強制適用と余白バグの除去
  clone.classList.add('force-pc-layout');
  clone.style.backdropFilter = 'none';
  clone.style.backgroundColor = '#151322'; 
  clone.style.boxShadow = 'none'; 

  const wrapper = document.createElement('div');
  wrapper.style.position = 'absolute';
  wrapper.style.top = '0';
  wrapper.style.left = '0';
  wrapper.style.zIndex = '-9999';
  wrapper.style.opacity = '0.01';
  wrapper.style.width = '1150px'; 
  wrapper.appendChild(clone);
  document.body.appendChild(wrapper);

  // 画像の縦伸び・ぼやけを防ぐ処理
  const cPortrait = clone.querySelector('.portrait-section');
  const cImg = clone.querySelector('#portrait-preview');
  const originalImg = document.getElementById('portrait-preview');

  if (cImg && cImg.src && originalImg.naturalWidth) {
    cImg.style.display = 'block';
    const rect = cPortrait.getBoundingClientRect();
    const cw = rect.width;
    const ch = rect.height;
    const iw = originalImg.naturalWidth;
    const ih = originalImg.naturalHeight;
    const cr = cw / ch;
    const ir = iw / ih;

    cImg.style.position = 'absolute';
    cImg.style.objectFit = 'fill'; 

    if (cr > ir) {
      const scaledHeight = cw / ir;
      cImg.style.width = cw + 'px';
      cImg.style.height = scaledHeight + 'px';
      cImg.style.left = '0px';
      cImg.style.top = ((ch - scaledHeight) / 2) + 'px';
    } else {
      const scaledWidth = ch * ir;
      cImg.style.width = scaledWidth + 'px';
      cImg.style.height = ch + 'px';
      cImg.style.top = '0px';
      cImg.style.left = ((cw - scaledWidth) / 2) + 'px';
    }
  }

  // ライセンス発行（画像出力）
  html2canvas(clone, {
    scale: 3, 
    backgroundColor: '#100e17', 
    useCORS: true,
    logging: false
  }).then(canvas => {
    const link = document.createElement('a');
    link.download = 'Ghostpunk_License.png';
    link.href = canvas.toDataURL('image/png');
    link.click();

    document.body.removeChild(wrapper);
    downloadBtn.textContent = originalText;
    downloadBtn.disabled = false;
  }).catch(err => {
    console.error('画像生成エラー:', err);
    alert('画像の生成に失敗しました。');
    document.body.removeChild(wrapper);
    downloadBtn.textContent = originalText;
    downloadBtn.disabled = false;
  });
});